name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Secret store
        run: echo "${{ secrets.TOKEN_NAME }} ${{ secrets.TOKEN_VALUE }} token name and values are store."
